listofstorageaccount:
  -  name: philmcitstorageaccount1
    account_tier: Standard
    account_replication_type: GRS
    access_tier: Cool
    cross_tenant_replication_enabled: enabled
  -  name: philmcitstorageaccount2
    account_tier: Standard
    account_replication_type: GRS
    access_tier: Cool
    cross_tenant_replication_enabled: enabled
